### ISSUE TITLE
Change Podfile to use HTTPS github reference

### ISSUE THREAD

**Issue by akfreas** [contentful/gallery-app-ios#1]
It should be 
`https://github.com/neonichu/ZoomInteractiveTransition.git`

instead of

`git@github.com:neonichu/ZoomInteractiveTransition.git`

Otherwise there is a publickey error since we don't have your keys :smiley:

**Comment by neonichu** [comment]
Fixed in 0afc328d23eb3febea934695123acbd89030e104 :)
